name: Black Duck PR Comment Demo
on:
    push:
      branches: [main, master]
    pull_request:
      branches: [main, master]

jobs:
    blackduck-prcomment:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Black Duck Scan with PR Comments
          uses: blackduck-inc/black-duck-security-scan@v2
          with:
            blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
            blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
            blackducksca_prComment_enabled: true
            github_token: ${{ secrets.TOKENACTION }}